name: Verify Homebrew Tarball

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag to verify (e.g. v0.1.2)
        required: false
        default: ''
  repository_dispatch:
    types: [verify-homebrew]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine tag and version
        id: tagvars
        shell: bash
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            tag="${{ github.event.inputs.tag }}"
          elif [[ -n "${{ github.event.client_payload.tag }}" ]]; then
            tag="${{ github.event.client_payload.tag }}"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            tag="${GITHUB_REF#refs/tags/}"
          else
            echo "::error ::No tag provided. Set workflow input 'tag'."
            exit 1
          fi
          version="${tag#v}"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run tests
        run: npm test

      - name: Fetch GitHub release tarball SHA
        id: remote
        shell: bash
        run: |
          remote_sha=$(curl -L --fail "https://github.com/clockworknet/codex-status/archive/refs/tags/${{ steps.tagvars.outputs.tag }}.tar.gz" | shasum -a 256 | awk '{print $1}')
          echo "sha=$remote_sha" >> "$GITHUB_OUTPUT"

      - name: Validate Homebrew formula entry
        shell: bash
        run: |
          url="url \"https://github.com/clockworknet/codex-status/archive/refs/tags/${{ steps.tagvars.outputs.tag }}.tar.gz\""
          sha="sha256 \"${{ steps.remote.outputs.sha }}\""
          grep -F "$url" HomebrewFormula/codex-status.rb
          grep -F "$sha" HomebrewFormula/codex-status.rb
